### ISSUE TITLE
로그인 회원가입 뷰 작업

### ISSUE THREAD

**Issue by haesol822** [2023-AHEUNGTHON/TEAM_8_2#3]
# 로그인 회원가입 뷰 작업

## 목적

- 뷰 퍼블리싱

## To-do

- [ ] /(작업한 페이지) - (작업 내용)  ex. /login - 로그인 뷰 퍼블리싱
- [ ] /Main - 뷰 퍼블리싱
- [ ] /Login - 뷰 퍼블리싱 및 임시 api 연동
- [ ] /Join - 뷰 퍼블리싱 및 임시 api 연동
- [ ] /Nickname - 뷰 퍼블리싱 작업 중

## 기타 참고 사항

-
